### PR TITLE
Nedim renesalis patch 2

### PR DESCRIPTION
**Pull request by NedimRenesalis**
I have changed the link to the Nonagon Finance logo, since the link in the last commit does not resolve the logo in the Gnosis frontend.

Please merge PR.

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Looks good to me @josojo. I don't think my approval counts though.

**Comment by NedimRenesalis** [comment]
Hi @josojo 

Please merge the PR.

Thank you

**Comment by NedimRenesalis** [comment]
Can anyone from the Gnosis team please merge the PR?

Thank you

**Comment by NedimRenesalis** [comment]
Hi, 
@fedgiac @ramirotw @koeppelmann @fqlx @0xslipk @cmagan @nsafari @Rafanator @baribari1 @NastaranGhaffari @alebanzas @rmeissner @samepant

who at Gnosis could please merge my PR?

Thank you

**Review by segun — APPROVED** [review]

**Pull request merged**
