### PR TITLE
Fix tokens in list

### PR DESCRIPTION
**Pull request by fedgiac**
I noticed that there were some issues in the token list that was recently uploaded.
This PR corrects them. The GNO token is listed twice, so a comment is added stating that it's a known property of the list.
@josojo, was this list automatically generated? I see a timestamp, so maybe we should investigate the tool used? 

### Test plan
Manual verification on Etherscan.
```

### CODE REVIEW

**Comment by josojo** [comment]
Thanks for noticing.

I think it was a requirement to show wbtc on both addresses, hence I would prefer to keep it as a doublicate. Other fixes are important ;)

**Review by josojo — APPROVED** [review]

**Comment by fedgiac** [comment]
I added a comment to the list for clarity, can I keep it there or should I also remove it?

**Comment by josojo** [comment]
If, it does not break anything, then lets keep it there...

I think we can just test it by merging, as it is very very unlikely...

**Comment by josojo** [comment]
Sorry, it actually broke it.
Wasn't able to fix it quickly, hence I reverted it.

**Pull request merged**
